// productsData.js

const cardDetail = [
    {
        image:"./images/001.png",
        tag: "#00001",
        name: "Bulbasaur",
        cardClass: 'Grass',
        cardClass2: 'Poison',
        age: 15,
    },
    {
        image:"./images/002.png",
        tag: "#00002",
        name: "Ivysaur",
        cardClass: 'Grass',
        cardClass2: 'Poison',
        age: 22,
    },
    {
        image:"./images/003-Gmax.png",
        tag: "#00003",
        name: "Venusaur",
        cardClass: 'Grass',
        cardClass2: 'Poison',
        age: 30,
    },
    {
        image:"./images/004.png",
        tag: "#00004",
        name: "Charmander",
        cardClass: 'Fire',
        cardClass2: '',
        age: 11,
    },
    {
        image:"./images/005.png",
        tag: "#00005",
        name: "Charmeleon",
        cardClass: 'Fire',
        cardClass2: '',
        age: 22,
    },
    {
        image:"./images/006.png",
        tag: "#00006",
        name: "Charizard",
        cardClass: 'Fire',
        cardClass2: 'Flying',
        age: 14,
    },
    {
        image:"./images/007.png",
        tag: "#00007",
        name: "Squirtle",
        cardClass: 'Water',
        cardClass2: '',
        age: 36,
    },
    {
        image:"./images/008.png",
        tag: "#00008",
        name: "Wartortle",
        cardClass: 'Water',
        cardClass2: '',
        age: 19,
    },
    {
        image:"./images/009.png",
        tag: "#00009",
        name: "Blastoise",
        cardClass: 'Water',
        cardClass2: '',
        age: 37,
    },
    {
        image:"./images/010.png",
        tag: "#00010",
        name: "Caterpie",
        cardClass: 'Bug',
        cardClass2: '',
        age: 25,
    },
    {
        image:"./images/011.png",
        tag: "#00011",
        name: "Metapod",
        cardClass: 'Bug',
        cardClass2: '',
        age: 10,
    },
    {
        image:"./images/012.png",
        tag: "#00012",
        name: "Butterfree",
        cardClass: 'Bug',
        cardClass2: 'Flying',
        age: 8,
    },
];

export default cardDetail;
